image:
  repository: ivicamaticsd/catapult-cs-stac-creator
  tag: dev
  pullPolicy: Always

nats:
    host: "ha-nats"
    port: 4222
    itemChannel: "stac_creator.item"
    collectionChannel: "stac_creator.collection"

s3:
    accessKeyId: "not-needed-s3-proxy"
    secretKeyId: "not-needed-s3-proxy"
    region: "eu-west-2"
    bucket: "ard-bucket"
    endpoint: "http://s3-proxy:80"
    imageryPath: "common_sensing"
    stacPath: "stac_catalogs/cs_stac"

storageFullQualifiedDomainName: "https://testingcommonsensing.blob.core.windows.net"